#!/usr/bin/env sh
# Turns "Upper Case.pdf" files into "upper-case.pdf" files
ext=$1

if [ -z "$ext" ]; then
  ext="pdf"
fi

for file in *."$ext"; do
  mv "$file" "$(echo "$file" | sed -e 's/ /-/g' -e 's/---/-/g' | tr '[:upper:]' '[:lower:]')"
done
