#!/bin/bash
# Find all people who have worked on each file in com.autovend.software*
find com.autovend.software* -name '*.java' -print0 | while read -r -d $'\0' file; do
  echo "$file"
  git blame "$file" -p | grep "^author " | sed 's/^/@/' | uniq | sort -u
  printf "\n"
done
