#!/bin/bash
# Converts hex colours to rgb
# https://www.chucknemeth.com/linux/ricing/virtual_terminal_color
# https://www.chucknemeth.com/_export/code/linux/ricing/virtual_terminal_color?codeblock=3
hexinput=$(echo "$1" | tr '[:lower:]' '[:upper:]' | sed 's/#//g')
printf "%d\n%d\n%d\n" "0x${hexinput:0:2}" "0x${hexinput:2:2}" "0x${hexinput:4:2}"
