#!/usr/bin/env bash
# Inspired by https://gitlab.com/dwt1/dmscripts/-/blob/master/scripts/dm-wiki
source "/home/omar/Scripts/dmenu/config"

wikidir="/usr/share/doc/arch-wiki/html/en/"
choice=$(fd . "${wikidir}" -e html | \
        cut -d '/' -f8- | \
        sed -e 's/_/ /g' -e 's/.html//g' | \
        sort -g | \
        ${DMENU:-dmenu} -p "Arch Wiki Docs: " -l 20 "$@") || exit 1

[ -n "$choice" ] && 
  firefox "$(echo "${wikidir}${choice}.html" | sed 's/ /_/g')"
