#!/usr/bin/env bash

# Example output
# $ HIST 200
# % History of Writing
# % Mon, 13 Sept, 2021

help(){
cat << EOF
USAGE: notes-start [-h | --help] [-o | --output]
        [-c | --class] [-t | --topic]
EOF
}

temp=$(getopt -o hc:t:o:: -l help,class:,topic:,output:: -n 'notes-start' -- "$@")

if [ $? != 0 ]; then help; echo "Terminating...">&2; exit 1; fi

eval set -- "$temp"

file=/dev/stdout
is_default_class=true
is_default_topic=true
class="[INSERT CLASS HERE]"
topic="[INSERT TOPIC HERE]"
while true; do
  case "$1" in
    -h | --help ) help; exit 0 ;;
    -c | --class ) class=$2; is_default_class=false; shift 2 ;;
    -t | --topic ) topic=$2; is_default_topic=false; shift 2 ;;
    -o | --output ) [[ -z "$2" ]] && file=./notes.md || file="$2"; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

if [[ -f "$file" && "$file" != /dev/stdout ]]; then
  choice="n"
  read -rp "WARNING: The following process will overwrite a pre-existing \
version of $file! Would you like to continue? [y/n] (n): " choice

  if [[ "$choice" != "y" ]]; then echo "Terminating..." >&2; exit 1; fi
fi

if [[ $is_default_class == true ]]; then
  choice=""
  read -rp "Enter class name: " choice
  if [[ -n "${choice// }" ]]; then
    class="$choice"
  fi
fi

if [[ $is_default_topic == true ]]; then
  choice=""
  read -rp "Enter topic name: " choice
  if [[ -n "${choice// }" ]]; then
    topic="$choice"
  fi
fi

echo -e "# $class\n\n> $topic\n\n> $(date +"%A, %B %-d, %Y")" > "$file"
